/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as enrollCmd } from './commands/enroll.ts';
import type { command as installcronCmd } from './commands/install-cron.ts';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as statusCmd } from './commands/status.ts';
import type { command as syncCmd } from './commands/sync.ts';
import type { command as uninstallcronCmd } from './commands/uninstall-cron.ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'enroll': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'install-cron': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'status': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'sync': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'uninstall-cron': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'enroll': {
      segment: { kind: 'literal', value: 'enroll' },
      command: { path: 'enroll', load: () => import('./commands/enroll.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'install-cron': {
      segment: { kind: 'literal', value: 'install-cron' },
      command: { path: 'install-cron', load: () => import('./commands/install-cron.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'status': {
      segment: { kind: 'literal', value: 'status' },
      command: { path: 'status', load: () => import('./commands/status.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'sync': {
      segment: { kind: 'literal', value: 'sync' },
      command: { path: 'sync', load: () => import('./commands/sync.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'uninstall-cron': {
      segment: { kind: 'literal', value: 'uninstall-cron' },
      command: { path: 'uninstall-cron', load: () => import('./commands/uninstall-cron.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
  },
  paramChild: null,
};
